CREATE TABLE FILMS_RATING (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DIRECTOR VARCHAR(255) NOT NULL,
    BUDGET FLOAT NOT NULL,
    RATING FLOAT NOT NULL,
    PRIMARY KEY (ID)
);
